# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-30 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('ch1', models.CharField(max_length=100)),
                ('ch2', models.CharField(max_length=100)),
                ('ch3', models.CharField(max_length=100)),
                ('ch4', models.CharField(max_length=100)),
            ],
        ),
    ]
