# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-11 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ch1',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='ch2',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='ch3',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='ch4',
            field=models.TextField(max_length=100),
        ),
    ]
