# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_stan'),
    ]

    operations = [
        migrations.AddField(
            model_name='stan',
            name='reponse',
            field=models.CharField(default='0000000', max_length=200),
        ),
    ]
